### PR TITLE
convert ng in ngTagsInput to cm

### PR DESCRIPTION
**Pull request by chaudhryjunaid**

### CODE REVIEW

**Comment by chaudhryjunaid** [comment]
@neebz this is the fix for ng-tags-input customization. I have changed the latest version of the module, all directives and templates to use cm instead of ng as a prefix. I have published this module to https://www.npmjs.com/package/cm-tags-input and converted family code to use this latest one instead of version 2.1.1 and applied customizations to this. It is now working fine in family calendar and I am using ng-tags-input separately in todos in app_caremerge successfully with default behavior.

**Comment by chaudhryjunaid** [comment]
@neebz by the way, this module contains rockstar code including 346 tests!

**Comment by neebz** [comment]
neat - if it works then merge it.

**Comment by chaudhryjunaid** [comment]
@neebz yes, all tests passing and calendar module working fine.

**Pull request merged**
